package com.hdu.tx.aschool.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACT_INFO".
 */
public class ActInfo implements java.io.Serializable {

    private Long id;
    private String hostname;
    private String imageUrl;
    private String hostimageUrl;
    private String title;
    private String actId;
    private String aid;
    private String time;
    private String address;
    private String describe;
    private String hostId;
    private Integer lookTimes;
    private Integer collectTimes;
    private Integer totalpeopel;
    private Integer joinedpeopel;
    private Boolean isCollect;
    private Boolean isJoin;
    private Boolean isHost;

    public ActInfo() {
    }

    public ActInfo(Long id) {
        this.id = id;
    }

    public ActInfo(Long id, String hostname, String imageUrl, String hostimageUrl, String title, String actId, String aid, String time, String address, String describe, String hostId, Integer lookTimes, Integer collectTimes, Integer totalpeopel, Integer joinedpeopel, Boolean isCollect, Boolean isJoin, Boolean isHost) {
        this.id = id;
        this.hostname = hostname;
        this.imageUrl = imageUrl;
        this.hostimageUrl = hostimageUrl;
        this.title = title;
        this.actId = actId;
        this.aid = aid;
        this.time = time;
        this.address = address;
        this.describe = describe;
        this.hostId = hostId;
        this.lookTimes = lookTimes;
        this.collectTimes = collectTimes;
        this.totalpeopel = totalpeopel;
        this.joinedpeopel = joinedpeopel;
        this.isCollect = isCollect;
        this.isJoin = isJoin;
        this.isHost = isHost;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHostname() {
        return hostname;
    }

    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getHostimageUrl() {
        return hostimageUrl;
    }

    public void setHostimageUrl(String hostimageUrl) {
        this.hostimageUrl = hostimageUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getActId() {
        return actId;
    }

    public void setActId(String actId) {
        this.actId = actId;
    }

    public String getAid() {
        return aid;
    }

    public void setAid(String aid) {
        this.aid = aid;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getHostId() {
        return hostId;
    }

    public void setHostId(String hostId) {
        this.hostId = hostId;
    }

    public Integer getLookTimes() {
        return lookTimes;
    }

    public void setLookTimes(Integer lookTimes) {
        this.lookTimes = lookTimes;
    }

    public Integer getCollectTimes() {
        return collectTimes;
    }

    public void setCollectTimes(Integer collectTimes) {
        this.collectTimes = collectTimes;
    }

    public Integer getTotalpeopel() {
        return totalpeopel;
    }

    public void setTotalpeopel(Integer totalpeopel) {
        this.totalpeopel = totalpeopel;
    }

    public Integer getJoinedpeopel() {
        return joinedpeopel;
    }

    public void setJoinedpeopel(Integer joinedpeopel) {
        this.joinedpeopel = joinedpeopel;
    }

    public Boolean getIsCollect() {
        return isCollect;
    }

    public void setIsCollect(Boolean isCollect) {
        this.isCollect = isCollect;
    }

    public Boolean getIsJoin() {
        return isJoin;
    }

    public void setIsJoin(Boolean isJoin) {
        this.isJoin = isJoin;
    }

    public Boolean getIsHost() {
        return isHost;
    }

    public void setIsHost(Boolean isHost) {
        this.isHost = isHost;
    }

}
