package com.hdu.tx.aschool.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACTI_DAO".
 */
public class ActiDao {

    private Long id;
    private String hostname;
    private String imageUrl;
    private String title;
    private String time;
    private String address;
    private String describe;
    private Integer totalpeopel;
    private Integer joinedpeopel;

    public ActiDao() {
    }

    public ActiDao(Long id) {
        this.id = id;
    }

    public ActiDao(Long id, String hostname, String imageUrl, String title, String time, String address, String describe, Integer totalpeopel, Integer joinedpeopel) {
        this.id = id;
        this.hostname = hostname;
        this.imageUrl = imageUrl;
        this.title = title;
        this.time = time;
        this.address = address;
        this.describe = describe;
        this.totalpeopel = totalpeopel;
        this.joinedpeopel = joinedpeopel;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHostname() {
        return hostname;
    }

    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public Integer getTotalpeopel() {
        return totalpeopel;
    }

    public void setTotalpeopel(Integer totalpeopel) {
        this.totalpeopel = totalpeopel;
    }

    public Integer getJoinedpeopel() {
        return joinedpeopel;
    }

    public void setJoinedpeopel(Integer joinedpeopel) {
        this.joinedpeopel = joinedpeopel;
    }

}
