package com.hdu.tx.aschool.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hdu.tx.aschool.dao.UserInfo;
import com.hdu.tx.aschool.dao.ActiDao;

import com.hdu.tx.aschool.dao.UserInfoDao;
import com.hdu.tx.aschool.dao.ActiDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig actiDaoDaoConfig;

    private final UserInfoDao userInfoDao;
    private final ActiDaoDao actiDaoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        actiDaoDaoConfig = daoConfigMap.get(ActiDaoDao.class).clone();
        actiDaoDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        actiDaoDao = new ActiDaoDao(actiDaoDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(ActiDao.class, actiDaoDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        actiDaoDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public ActiDaoDao getActiDaoDao() {
        return actiDaoDao;
    }

}
