package com.hdu.tx.aschool.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hdu.tx.aschool.dao.UserInfo;
import com.hdu.tx.aschool.dao.ActInfo;
import com.hdu.tx.aschool.dao.InputString;

import com.hdu.tx.aschool.dao.UserInfoDao;
import com.hdu.tx.aschool.dao.ActInfoDao;
import com.hdu.tx.aschool.dao.InputStringDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig actInfoDaoConfig;
    private final DaoConfig inputStringDaoConfig;

    private final UserInfoDao userInfoDao;
    private final ActInfoDao actInfoDao;
    private final InputStringDao inputStringDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        actInfoDaoConfig = daoConfigMap.get(ActInfoDao.class).clone();
        actInfoDaoConfig.initIdentityScope(type);

        inputStringDaoConfig = daoConfigMap.get(InputStringDao.class).clone();
        inputStringDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        actInfoDao = new ActInfoDao(actInfoDaoConfig, this);
        inputStringDao = new InputStringDao(inputStringDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(ActInfo.class, actInfoDao);
        registerDao(InputString.class, inputStringDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        actInfoDaoConfig.getIdentityScope().clear();
        inputStringDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public ActInfoDao getActInfoDao() {
        return actInfoDao;
    }

    public InputStringDao getInputStringDao() {
        return inputStringDao;
    }

}
