package com.hdu.tx.aschool.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.hdu.tx.aschool.dao.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, Long> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Username = new Property(1, String.class, "username", false, "USERNAME");
        public final static Property Nickname = new Property(2, String.class, "nickname", false, "NICKNAME");
        public final static Property Level = new Property(3, Integer.class, "level", false, "LEVEL");
        public final static Property School = new Property(4, String.class, "school", false, "SCHOOL");
        public final static Property Major = new Property(5, String.class, "major", false, "MAJOR");
        public final static Property Headimg_url = new Property(6, String.class, "headimg_url", false, "HEADIMG_URL");
        public final static Property PhoneNumber = new Property(7, String.class, "phoneNumber", false, "PHONE_NUMBER");
        public final static Property IsBindPhone = new Property(8, Boolean.class, "isBindPhone", false, "IS_BIND_PHONE");
        public final static Property Grade = new Property(9, String.class, "grade", false, "GRADE");
        public final static Property Institute = new Property(10, String.class, "institute", false, "INSTITUTE");
    };


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USERNAME\" TEXT," + // 1: username
                "\"NICKNAME\" TEXT," + // 2: nickname
                "\"LEVEL\" INTEGER," + // 3: level
                "\"SCHOOL\" TEXT," + // 4: school
                "\"MAJOR\" TEXT," + // 5: major
                "\"HEADIMG_URL\" TEXT," + // 6: headimg_url
                "\"PHONE_NUMBER\" TEXT," + // 7: phoneNumber
                "\"IS_BIND_PHONE\" INTEGER," + // 8: isBindPhone
                "\"GRADE\" TEXT," + // 9: grade
                "\"INSTITUTE\" TEXT);"); // 10: institute
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(3, nickname);
        }
 
        Integer level = entity.getLevel();
        if (level != null) {
            stmt.bindLong(4, level);
        }
 
        String school = entity.getSchool();
        if (school != null) {
            stmt.bindString(5, school);
        }
 
        String major = entity.getMajor();
        if (major != null) {
            stmt.bindString(6, major);
        }
 
        String headimg_url = entity.getHeadimg_url();
        if (headimg_url != null) {
            stmt.bindString(7, headimg_url);
        }
 
        String phoneNumber = entity.getPhoneNumber();
        if (phoneNumber != null) {
            stmt.bindString(8, phoneNumber);
        }
 
        Boolean isBindPhone = entity.getIsBindPhone();
        if (isBindPhone != null) {
            stmt.bindLong(9, isBindPhone ? 1L: 0L);
        }
 
        String grade = entity.getGrade();
        if (grade != null) {
            stmt.bindString(10, grade);
        }
 
        String institute = entity.getInstitute();
        if (institute != null) {
            stmt.bindString(11, institute);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // username
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nickname
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // level
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // school
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // major
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // headimg_url
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // phoneNumber
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // isBindPhone
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // grade
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // institute
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUsername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNickname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLevel(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setSchool(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMajor(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setHeadimg_url(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPhoneNumber(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsBindPhone(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setGrade(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setInstitute(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
